-- SQLite

CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR (30) NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONE VARCHAR (20) NOT NULL,
    EMAIL VARCHAR (30) NOT NULL,
    ADDRESS TEXT NOT NULL,
    CITY VARCHAR (30) NOT NULL,
    STATE VARCHAR (2) NOT NULL,
    BIRTH_DATE DATE NOT NULL
);
