-- SQLite

SELECT  CUSTOMERS.NAME AS 'Nome do cliente', 
        COUNT(LOCATIONS.ID) AS 'Locações feitas' FROM LOCATIONS

        JOIN CUSTOMERS ON (LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
        GROUP BY CUSTOMERS.ID
        HAVING COUNT(LOCATIONS.ID) >= 2;