-- SQLite

SELECT  EMPLOYEES.NAME AS 'Nome', 
        COUNT(LOCATIONS.ID) AS 'Locações feitas' FROM LOCATIONS

        JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID)
        GROUP BY EMPLOYEES.ID
        HAVING COUNT(LOCATIONS.ID) >= 2;